# Generated by Django 4.1.5 on 2023-02-28 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sales.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_customuser_is_employee_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=120)),
                ('car_brand', models.CharField(choices=[('Mercedes', 'Mercedes'), ('Renault', 'Renault'), ('Fuso', 'Fuso')], max_length=120)),
                ('car_type', models.CharField(choices=[('Sedan', 'Sedan'), ('Van', 'Van'), ('Bus', 'Bus'), ('Sedan', 'Sedan'), ('Crossover', 'Crossover'), ('SUV', 'SUV'), ('Micro', 'Micro'), ('Hatchback', 'Hatchback'), ('Electric Car', 'Electric Car'), ('Truck', 'Truck')], max_length=80)),
                ('seating_capacity', models.CharField(max_length=200)),
                ('number_of_door', models.IntegerField(null=True)),
                ('payload', models.IntegerField(null=True)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel')], max_length=120)),
                ('car_engine', models.CharField(max_length=120, null=True)),
                ('horse_power', models.IntegerField()),
                ('emission_standard', models.CharField(max_length=100)),
                ('gearbox_type', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=120, null=True)),
                ('number_of_gears', models.IntegerField(null=True)),
                ('transmission', models.CharField(max_length=10)),
                ('anti_lock_braking_system', models.BooleanField(default=False)),
                ('servo_brakes', models.CharField(max_length=100, null=True)),
                ('wheel_rim_type', models.CharField(max_length=100, null=True)),
                ('spare_wheel', models.BooleanField(default=False, null=True)),
                ('air_constioning_type', models.CharField(max_length=100, null=True)),
                ('seats_upholesty', models.CharField(max_length=100, null=True)),
                ('seat_trim', models.CharField(max_length=100, null=True)),
                ('electromotor_door_locking', models.CharField(max_length=100, null=True)),
                ('length', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('wheel_base', models.IntegerField(null=True)),
                ('ground_clearance', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('review_title', models.CharField(max_length=120)),
                ('review_description', models.CharField(max_length=500)),
                ('reviewer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.cars')),
            ],
        ),
        migrations.CreateModel(
            name='PanaromicCarImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=sales.models.upload_to_panaroma)),
                ('is_exterior', models.BooleanField(null=True)),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.cars')),
            ],
        ),
        migrations.CreateModel(
            name='CarImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=sales.models.upload_to)),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.cars')),
            ],
        ),
    ]
