# Generated by Django 4.1.5 on 2023-03-03 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimages',
            name='cars',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='car_images', to='sales.cars'),
        ),
    ]
