# Generated by Django 4.1.5 on 2023-03-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_carimages_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_engine',
            field=models.IntegerField(null=True),
        ),
    ]
