# Generated by Django 4.1.5 on 2023-03-06 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_cars_car_engine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='car_engine',
            new_name='displacement',
        ),
    ]
