# Generated by Django 4.1.5 on 2023-03-07 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_rename_car_engine_cars_displacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='year',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cars',
            name='spare_wheel',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
