# Generated by Django 4.1.7 on 2023-03-16 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_cars_year_alter_cars_spare_wheel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='air_constioning_type',
            new_name='air_conditioning_type',
        ),
        migrations.AddField(
            model_name='cars',
            name='car_price',
            field=models.IntegerField(default=1200000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='protection_element',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='safety_belt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='anti_lock_braking_system',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
